config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

  devise_scope :user do
    get 'join', to: 'devise/registrations#new', as: :join
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign-out' => 'devise/sessions#destroy', :as => :sign_out
  end

  resources :posts, path: "forum" do
  	resources :comments, path: "post"
  end

  root 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates  :comment, presence: true

  # For notifications
  def send_notifications!
    users = post.users.uniq - [user]
    users.each do |user|
    	NotificationMailer.comment_notification(user, self).deliver_later
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  
  # For notifications
  has_many :users, through: :comments

  validates :title, :content, :category_id, presence: true
  validates :title, length: {minimum: 5, maximum: 100}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  #Login with username or email
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

  validates :username, presence: true, length: {maximum: 24}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "can only contain letters and numbers, and be a maximum of 24 characters." }

  #Avatar
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ":style/user.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :username, :email, :avatar, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save

  	if @comment.save
      # For notifications
      @comment.send_notifications!
      
      redirect_to post_path(@post, anchor: "comment_#{@comment.id}")
  	else
  	  redirect_to post_path(@post), alert: 'Unable to save your post.'
    end
  end

  def edit
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
  	@comment = @post.comments.find(params[:id])

  	if @comment.update(params[:comment].permit(:comment))
  	  redirect_to post_path(@post, anchor: "comment_#{@comment.id}")
  	else
  	  render 'edit'
  	end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:category].blank?
		  @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
		else
		  @category_id = Category.find_by(name: params[:category]).id
		  @posts = Post.where(category_id: @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 10)
		end
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post, notice: "Your post has been submitted!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post, notice: "Your post has been updated!"
    else
    	render 'edit'
    end
	end

	def destroy
	  @post.destroy
	  redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active(path)
    "active" if current_page?(path)
  end

  def markdown(content)
  	@markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, {
  		hard_wrap: true,
      autolink: true,
      space_after_headers: true,
      underline: true,
      no_intraemphasis: true,
      filter_html: true,
  	})
  	@markdown.render(content)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
= div_for comment do

  %div.user-image
    = image_tag comment.user.avatar.url(:thumb)

  %div.post-reply

    %p.username
      = comment.user.username

    %p.date
      = time_ago_in_words(comment.created_at)
      ago

    %div.post-body-text
      = markdown(comment.comment).html_safe

    - if comment.user == current_user || current_user.try(:admin?)
      %div.edit-container
        = link_to "Edit", edit_post_comment_path(comment.post, comment), :class => 'edit'
      
        - if current_user.try(:admin?)
          = link_to " Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }, :class => 'delete'

%hr

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|

  = f.label :comment, required: false, :class => 'hide'
  = f.text_area :comment
  
  %span
    = f.submit "Reply"

app/views/comments/edit.html.haml
%div.container.form-container
  %div.eight
    %h1 Edit Reply
    = simple_form_for([@post, @comment]) do |f|
      = f.label :comment, required: false, :class => 'hide'
      = f.text_area :comment
      = f.submit "Reply"

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
%head
  %meta{:charset => "utf-8"}
  %meta{:name => "description", :content => ""}
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
  %title Conditioning Centre Community
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body

  %div.wrapper
    %header
      %div.container

        = link_to '', root_path, :class => 'logo'

        %a.navicon-button
          %div.navicon

        %nav
          %span
            = link_to 'Discussions', root_path
          %span
            = link_to 'Videos', root_path
          %span
            = link_to 'Programs', root_path
          %span
            - if user_signed_in?
              %a.clicker.social-icon.icon-chevron-down<
                = current_user.username
              %div.dropdown
                %span
                  = link_to 'Account', edit_user_registration_path
                %span
                  = link_to 'Billing', edit_user_registration_path
                %span
                  = link_to('Sign Out', sign_out_path, method: :delete)
            - else
              %span
                = link_to "Sign In", sign_in_path
    
    - if notice
      %div.alert-container
        %p.notice= notice
    - if alert
      %div.alert-container
        %p.alert= alert

    = yield

%footer
  %div.container
    %div.six
      %p.copyright 
        Copyright &copy; The Conditioning Centre
        = Time.now.year
        <br>
        Registered in England No.8933965
    %div.six
      %div.social-icons
        %a{ :href => "#", :class => "social-icon icon-facebook" }
        %a{ :href => "#", :class => "social-icon icon-twitter" }
        %a{ :href => "#", :class => "social-icon icon-google-plus" }
        %a{ :href => "#", :class => "social-icon icon-youtube" }

app/views/posts/_form.html.haml
= simple_form_for @post do |f|

  - if @post.errors.any?
    %h2
      = pluralize(@post.errors.count, "error")
      prohibited this mark from being saved:
    %ul
      - @post.errors.full_messages.each do |message|
        %li
          = message

  %div.form-top
    %div.form-left
      = f.label :title, required: false
      = f.text_field :title, autofocus: true
    %div.form-right
      = f.label :category_id, required: false
      = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"}

  = f.label :content, required: false
  = f.text_area :content

  = f.submit "Submit"

app/views/posts/_no_posts.html.haml
%p.no-posts 
  There are no posts in this Category at the momment.

app/views/posts/edit.html.haml
%div.container.form-container
  %div.eight
    %h1 Edit Post
    = render 'form'

app/views/posts/index.html.haml
%section.hero
  %div.container.hero-inner
    %h1.huge
      Discussions

%section.forum-header
  %div.container
    %h2.large.headline
      Welcome to the discussions forum. Get help &amp; advice on Excercise, Nutrition &amp; Mobilty.
    %span
      - if !user_signed_in?
        = link_to "Join the Team", join_path,
          { :class => "button" }

%section.forum-content
  %div.container
        
    %div.forum-posts
      %div.nine.forum-posts-container

        - if @posts.size > 0

          - @posts.each do |post|
            %div.single-post-container
              %div.user-image
                = image_tag post.user.avatar.url(:thumb)
              %div.forum-post
                %h2= link_to post.title, post
                %p
                  %em
                    Posted
                    = time_ago_in_words(post.created_at)
                    ago by
                    %strong
                      = post.user.username
                    in
                    %strong
                      = post.category.name

              %div.forum-replies
                %p
                  - if post.comments.count == 1
                    = post.comments.count
                    %span Reply
                  - else
                    = post.comments.count
                    %span Replies 

              %hr

          = will_paginate @posts, previous_label: "Previous", next_label: "Next", inner_window: 1, outer_window: 0

        - else
          = render partial: "no_posts"

    %div.category-sidebar
      %div.three.category-container
        %span
          - if user_signed_in?
            = link_to "New Post", new_post_path,
              { :class => "button" }
        %nav
          %span
            = link_to "All Topics", root_path, class: "#{active(root_path)}"
          %hr 
          - Category.all.each do |category|
            %span
              = link_to category.name, posts_path(category: category.name), class: "#{active(posts_path(category: category.name))}"
            %hr

app/views/posts/new.html.haml
%div.container.form-container
  %div.eight
    %h1 New Post
    = render 'form'

app/views/posts/show.html.haml
%div.forum-show
  %div.container
    %div.nine
      %div.post-nav

        = link_to "Back to Forum", root_path, :class => 'back icon-arrow-left2'

        %div.edit-container
          - if @post.user == current_user || current_user.try(:admin?)
            = link_to "Edit", edit_post_path(@post), :class => 'edit'

          - if current_user.try(:admin?)
            = link_to " Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?"}, :class => 'delete'

      %div.post-container
        %div.user-image
          = image_tag @post.user.avatar.url(:thumb)

        %div.post
          %h1= @post.title

          %p.meta
            %em
              Posted
              = time_ago_in_words(@post.created_at)
              ago by
              %strong
                = @post.user.username
              in
              %strong
                = @post.category.name

          %div.post-body-text
            = markdown(@post.content).html_safe

      - if @post.comments.count > 0
        %div.replies-container

          %h2
            - if @post.comments.count == 1 
              = @post.comments.count
              Reply
            - else
              = @post.comments.count
              Replies

          %hr

          = render @post.comments

      %div.reply-form
        %h3 Add a Reply

        - if user_signed_in?
          = render "comments/form"
        - else
          %p 
            You need to 
            %strong Sign In 
            or 
            %strong Sign Up 
            before you can add a reply.
          %div.reply-buttons-container
            %span
              = link_to "Sign in", sign_in_path,
              { :class => "button" }
            %span
              = link_to "Sign up", join_path,
              { :class => "button" }